// SPDX-License-Identifier: (GPL-2.0 OR MIT)
/*
 * Copyright (c) 2024 MediaTek Inc.
 * Author: Chris-qj Chen <chris-qj.chen@mediatek.com>
 */

#include <common.h>
#include <dm.h>
#include <asm/io.h>
#include <dt-bindings/clock/mt8195-clk.h>
#include <linux/bitops.h>

#include "clk-mtk.h"

static const struct mtk_gate_regs vpp1_0_cg_regs = {
	.set_ofs = 0x104,
	.clr_ofs = 0x108,
	.sta_ofs = 0x100,
};

static const struct mtk_gate_regs vpp1_1_cg_regs = {
	.set_ofs = 0x114,
	.clr_ofs = 0x118,
	.sta_ofs = 0x110,
};

#define GATE_VPP1_0(_id, _parent, _shift)			\
	GATE_MTK_FLAGS(_id, _parent, &vpp1_0_cg_regs, _shift,\
		CLK_PARENT_TOPCKGEN | CLK_GATE_SETCLR)

#define GATE_VPP1_1(_id, _parent, _shift)			\
	GATE_MTK_FLAGS(_id, _parent, &vpp1_1_cg_regs, _shift,\
		CLK_PARENT_TOPCKGEN | CLK_GATE_SETCLR)

static const struct mtk_gate vpp1_clks[] = {
	/* VPP1_0 */
	GATE_VPP1_0(CLK_VPP1_SVPP1_MDP_OVL, CLK_TOP_VPP, 0),
	GATE_VPP1_0(CLK_VPP1_SVPP1_MDP_TCC, CLK_TOP_VPP, 1),
	GATE_VPP1_0(CLK_VPP1_SVPP1_MDP_WROT, CLK_TOP_VPP, 2),
	GATE_VPP1_0(CLK_VPP1_SVPP1_VPP_PAD, CLK_TOP_VPP, 3),
	GATE_VPP1_0(CLK_VPP1_SVPP2_MDP_WROT, CLK_TOP_VPP, 4),
	GATE_VPP1_0(CLK_VPP1_SVPP2_VPP_PAD, CLK_TOP_VPP, 5),
	GATE_VPP1_0(CLK_VPP1_SVPP3_MDP_WROT, CLK_TOP_VPP, 6),
	GATE_VPP1_0(CLK_VPP1_SVPP3_VPP_PAD, CLK_TOP_VPP, 7),
	GATE_VPP1_0(CLK_VPP1_SVPP1_MDP_RDMA, CLK_TOP_VPP, 8),
	GATE_VPP1_0(CLK_VPP1_SVPP1_MDP_FG, CLK_TOP_VPP, 9),
	GATE_VPP1_0(CLK_VPP1_SVPP2_MDP_RDMA, CLK_TOP_VPP, 10),
	GATE_VPP1_0(CLK_VPP1_SVPP2_MDP_FG, CLK_TOP_VPP, 11),
	GATE_VPP1_0(CLK_VPP1_SVPP3_MDP_RDMA, CLK_TOP_VPP, 12),
	GATE_VPP1_0(CLK_VPP1_SVPP3_MDP_FG, CLK_TOP_VPP, 13),
	GATE_VPP1_0(CLK_VPP1_VPP_SPLIT, CLK_TOP_VPP, 14),
	GATE_VPP1_0(CLK_VPP1_SVPP2_VDO0_DL_RELAY, CLK_TOP_VPP, 15),
	GATE_VPP1_0(CLK_VPP1_SVPP1_MDP_TDSHP, CLK_TOP_VPP, 16),
	GATE_VPP1_0(CLK_VPP1_SVPP1_MDP_COLOR, CLK_TOP_VPP, 17),
	GATE_VPP1_0(CLK_VPP1_SVPP3_VDO1_DL_RELAY, CLK_TOP_VPP, 18),
	GATE_VPP1_0(CLK_VPP1_SVPP2_VPP_MERGE, CLK_TOP_VPP, 19),
	GATE_VPP1_0(CLK_VPP1_SVPP2_MDP_COLOR, CLK_TOP_VPP, 20),
	GATE_VPP1_0(CLK_VPP1_VPPSYS1_GALS, CLK_TOP_VPP, 21),
	GATE_VPP1_0(CLK_VPP1_SVPP3_VPP_MERGE, CLK_TOP_VPP, 22),
	GATE_VPP1_0(CLK_VPP1_SVPP3_MDP_COLOR, CLK_TOP_VPP, 23),
	GATE_VPP1_0(CLK_VPP1_VPPSYS1_LARB, CLK_TOP_VPP, 24),
	GATE_VPP1_0(CLK_VPP1_SVPP1_MDP_RSZ, CLK_TOP_VPP, 25),
	GATE_VPP1_0(CLK_VPP1_SVPP1_MDP_HDR, CLK_TOP_VPP, 26),
	GATE_VPP1_0(CLK_VPP1_SVPP1_MDP_AAL, CLK_TOP_VPP, 27),
	GATE_VPP1_0(CLK_VPP1_SVPP2_MDP_HDR, CLK_TOP_VPP, 28),
	GATE_VPP1_0(CLK_VPP1_SVPP2_MDP_AAL, CLK_TOP_VPP, 29),
	GATE_VPP1_0(CLK_VPP1_DL_ASYNC, CLK_TOP_VPP, 30),
	GATE_VPP1_0(CLK_VPP1_LARB5_FAKE_ENG, CLK_TOP_VPP, 31),
	/* VPP1_1 */
	GATE_VPP1_1(CLK_VPP1_SVPP3_MDP_HDR, CLK_TOP_VPP, 0),
	GATE_VPP1_1(CLK_VPP1_SVPP3_MDP_AAL, CLK_TOP_VPP, 1),
	GATE_VPP1_1(CLK_VPP1_SVPP2_VDO1_DL_RELAY, CLK_TOP_VPP, 2),
	GATE_VPP1_1(CLK_VPP1_LARB6_FAKE_ENG, CLK_TOP_VPP, 3),
	GATE_VPP1_1(CLK_VPP1_SVPP2_MDP_RSZ, CLK_TOP_VPP, 4),
	GATE_VPP1_1(CLK_VPP1_SVPP3_MDP_RSZ, CLK_TOP_VPP, 5),
	GATE_VPP1_1(CLK_VPP1_SVPP3_VDO0_DL_RELAY, CLK_TOP_VPP, 6),
	GATE_VPP1_1(CLK_VPP1_DISP_MUTEX, CLK_TOP_VPP, 7),
	GATE_VPP1_1(CLK_VPP1_SVPP2_MDP_TDSHP, CLK_TOP_VPP, 8),
	GATE_VPP1_1(CLK_VPP1_SVPP3_MDP_TDSHP, CLK_TOP_VPP, 9),
	GATE_VPP1_1(CLK_VPP1_VPP0_DL1_RELAY, CLK_TOP_VPP, 10),
	GATE_VPP1_1(CLK_VPP1_HDMI_META, CLK_TOP_HDMIRX_P, 11),
	GATE_VPP1_1(CLK_VPP1_VPP_SPLIT_HDMI, CLK_TOP_HDMIRX_P, 12),
	GATE_VPP1_1(CLK_VPP1_DGI_IN, CLK_TOP_IN_DGI, 13),
	GATE_VPP1_1(CLK_VPP1_DGI_OUT,  CLK_TOP_DGI_OUT, 14),
	GATE_VPP1_1(CLK_VPP1_VPP_SPLIT_DGI, CLK_TOP_DGI_OUT, 15),
	GATE_VPP1_1(CLK_VPP1_VPP0_DL_ASYNC, CLK_TOP_VPP, 16),
	GATE_VPP1_1(CLK_VPP1_VPP0_DL_RELAY, CLK_TOP_VPP, 17),
	GATE_VPP1_1(CLK_VPP1_VPP_SPLIT_26M, CLK_TOP_CLK26M, 26),
};

extern const struct mtk_clk_tree mt8195_clk_tree;
static int mt8195_vpp1_probe(struct udevice *dev)
{
	return mtk_common_clk_gate_init(dev, &mt8195_clk_tree, vpp1_clks);
}

static const struct udevice_id of_match_clk_mt8195_vpp1[] = {
	{ .compatible = "mediatek,mt8195-vpp1", },
	{ }
};

U_BOOT_DRIVER(mtk_clk_vpp1) = {
	.name = "mt8195-vpp1",
	.id = UCLASS_CLK,
	.of_match = of_match_clk_mt8195_vpp1,
	.probe = mt8195_vpp1_probe,
	.priv_auto = sizeof(struct mtk_clk_priv),
	.ops = &mtk_clk_gate_ops,
	.flags = DM_FLAG_PRE_RELOC,
};
