# SPDX-License-Identifier: GPL-2.0
# Core
obj-y += clk-mtk.o

# SoC Drivers
obj-$(CONFIG_CLK_MTK_MT7623) += clk-mt7623.o
obj-$(CONFIG_CLK_MTK_MT7622) += clk-mt7622.o
obj-$(CONFIG_CLK_MTK_MT7629) += clk-mt7629.o
obj-$(CONFIG_CLK_MTK_MT7986) += clk-mt7986.o
obj-$(CONFIG_CLK_MTK_MT7981) += clk-mt7981.o
obj-$(CONFIG_CLK_MTK_MT7988) += clk-mt7988.o
obj-$(CONFIG_CLK_MTK_MT7987) += clk-mt7987.o
obj-$(CONFIG_CLK_MTK_MT8183) += clk-mt8183.o
obj-$(CONFIG_CLK_MTK_MT8186) += clk-mt8186.o
obj-$(CONFIG_CLK_MTK_MT8365) += clk-mt8365.o
obj-$(CONFIG_CLK_MTK_MT8512) += clk-mt8512.o
obj-$(CONFIG_CLK_MTK_MT8516) += clk-mt8516.o
obj-$(CONFIG_CLK_MTK_MT8518) += clk-mt8518.o
