#!/bin/sh

set -e

# Replace dc with U-Boot in the image

#old=/scratch/sglass/coral/chroot/build/coral/firmware/image-coral.dev.bin
old=/scratch/sglass/coral/chroot/build/coral/firmware/image-coral.bin

new=cb.bin
ub=/tmp/b/chromeos_coral
name=fallback/payload

cp $old $new

delete_locales() {
	for f in locale_tr.bin \
		locale_bg.bin \
		locale_hr.bin \
		locale_nl.bin \
		locale_ro.bin \
		locale_es.bin \
		locale_ja.bin \
		locale_el.bin \
		locale_pt-BR.bin \
		locale_de.bin \
		locale_lt.bin \
		locale_hi.bin \
		locale_vi.bin \
		locale_ca.bin \
		locale_hu.bin \
		locale_sr.bin \
		locale_pt-PT.bin \
		locale_fi.bin \
		locale_cs.bin \
		locale_he.bin \
		locale_fr.bin \
		locale_id.bin \
		locale_ta.bin \
		locale_bn.bin \
		locale_th.bin \
		locale_ar.bin \
		locale_it.bin \
		locale_pl.bin \
		locale_lv.bin \
		locale_mr.bin \
		locale_et.bin \
		locale_ms.bin \
		locale_nb.bin \
		locale_zh-CN.bin \
		locale_ko.bin \
		locale_fil.bin \
		locale_da.bin \
		locale_es-419.bin \
		locale_ru.bin \
		locale_uk.bin \
		locale_sl.bin \
		locale_te.bin \
		locale_sk.bin \
		locale_gu.bin \
		locale_sv.bin \
		locale_kn.bin \
		locale_ml.bin \
		locale_fa.bin \
		locale_zh-TW.bin \
		vbt-astronaut.bin vbt-epaulette.bin vbt-babytiger.bin \
		vbt-babymega.bin vbt-nasher.bin	vbt-rabbid_rugged.bin; do
		cbfstool $new remove -n $f
	done

}

# Process one region of the image
#  $1: region params ('' for recovery, '-r FW_MAIN_A' for firmare a)
do_part() {
	region="$1"

	cbfstool $new remove $region -n $name

	# Drop the unused bootblock in recovery to add space
	if [ -z "$region" ]; then
		 cbfstool $new remove $region -n bootblock
		delete_locales
	fi

	cbfstool $new expand $region

	if ! cbfstool $new add-flat-binary $region -n $name \
		-f $ub/u-boot.bin \
		-c lzma -l 0x1110000 -e 0x1110000; then
		cbfstool $new print $region
	fi
}

# Do read/write and recovery
do_part "-r FW_MAIN_A"
do_part "-r FW_MAIN_B"
do_part

# Put valid MRC-cache data in there for a faster boot
cbfstool $new write -r RW_MRC_CACHE -f RW_MRC_CACHE
cbfstool $new write -r RW_VAR_MRC_CACHE -f RW_VAR_MRC_CACHE
cbfstool $new write -r RECOVERY_MRC_CACHE -f RECOVERY_MRC_CACHE
