#
#
# Copyright (c) 2017 Google, Inc
#

obj-y += vboot-flag-uclass.o
obj-$(CONFIG_CROS_FLAG_CONST) += flag_const.o
obj-$(CONFIG_CROS_FLAG_GPIO) += flag_gpio.o
obj-$(CONFIG_CROS_FLAG_KEY) += flag_key.o
obj-$(CONFIG_CROS_FLAG_SYSINFO) += flag_sysinfo.o
