#
# Copyright (c) 2017 Google, Inc
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += nvdata-uclass.o
obj-$(CONFIG_NVDATA_CROS_EC) += nvdata_cros_ec.o
obj-$(CONFIG_$(SPL_TPL_)NVDATA_TPM) += nvdata_tpm.o
obj-$(CONFIG_NVDATA_CMOS) += nvdata_cmos.o
