# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test/py/cmdsock.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15test/py/cmdsock.proto\x1a\x0cnanopb.proto\"\x18\n\x05Hello\x12\x0f\n\x07version\x18\x01 \x02(\x05\"\x1f\n\x08StartReq\x12\x13\n\x04name\x18\x01 \x01(\tB\x05\x92?\x02\x08P\"-\n\tStartResp\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x0f\n\x07\x65rrcode\x18\x02 \x02(\x05\"\x1b\n\x04Puts\x12\x13\n\x03str\x18\x01 \x02(\tB\x06\x92?\x03\x08\x80\x02\".\n\tRunCmdReq\x12\x13\n\x03\x63md\x18\x01 \x02(\tB\x06\x92?\x03\x08\x80\x02\x12\x0c\n\x04\x66lag\x18\x02 \x02(\x05\"\x1c\n\nRunCmdResp\x12\x0e\n\x06result\x18\x01 \x02(\x05\"\xcb\x01\n\x07Message\x12\x17\n\x05hello\x18\x01 \x01(\x0b\x32\x06.HelloH\x00\x12\x1e\n\tstart_req\x18\x02 \x01(\x0b\x32\t.StartReqH\x00\x12 \n\nstart_resp\x18\x03 \x01(\x0b\x32\n.StartRespH\x00\x12\x15\n\x04puts\x18\x04 \x01(\x0b\x32\x05.PutsH\x00\x12!\n\x0brun_cmd_req\x18\x05 \x01(\x0b\x32\n.RunCmdReqH\x00\x12#\n\x0crun_cmd_resp\x18\x06 \x01(\x0b\x32\x0b.RunCmdRespH\x00\x42\x06\n\x04kind')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test.py.cmdsock_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STARTREQ.fields_by_name['name']._options = None
  _STARTREQ.fields_by_name['name']._serialized_options = b'\222?\002\010P'
  _PUTS.fields_by_name['str']._options = None
  _PUTS.fields_by_name['str']._serialized_options = b'\222?\003\010\200\002'
  _RUNCMDREQ.fields_by_name['cmd']._options = None
  _RUNCMDREQ.fields_by_name['cmd']._serialized_options = b'\222?\003\010\200\002'
  _HELLO._serialized_start=39
  _HELLO._serialized_end=63
  _STARTREQ._serialized_start=65
  _STARTREQ._serialized_end=96
  _STARTRESP._serialized_start=98
  _STARTRESP._serialized_end=143
  _PUTS._serialized_start=145
  _PUTS._serialized_end=172
  _RUNCMDREQ._serialized_start=174
  _RUNCMDREQ._serialized_end=220
  _RUNCMDRESP._serialized_start=222
  _RUNCMDRESP._serialized_end=250
  _MESSAGE._serialized_start=253
  _MESSAGE._serialized_end=456
# @@protoc_insertion_point(module_scope)
