# SPDX-License-Identifier: GPL-2.0+
# Copyright 2022 Google LLC
# Test code only, for Marek Vasut
#

# Support for iMX8mm signing

from collections import OrderedDict
import os

from binman.entry import EntryArg
from binman.etype.collection import Entry_collection

from dtoc import fdt_util
from patman import tools

class Entry_imx8mm_csf(Entry_collection):
    """An entry which contains ...

    Properties / Entry arguments:
        - content: List of phandles to entries to sign
        - other properties here

    Output files:
        - input.<unique_name> - input file passed to csf
        - csf.<unique_name> - output file generated by csf_util

    blurb here about what this does
    """
    def __init__(self, section, etype, node):
        super().__init__(section, etype, node)
        self.csf = None
        #(self.arg1, self.arg2) = self.GetEntryArgsOrProps([
            #EntryArg('keydir', str),
            #EntryArg('keyblock', str))

    def GetCsf(self, required):
        """Get the contents of this entry

        Args:
            required: True if the data must be present, False if it is OK to
                return None

        Returns:
            bytes content of the entry, which is the signed vblock for the
                provided data
        """
        # Join up the data files to be signed
        input_data = self.GetContents(required)
        if input_data is None:
            return None

        uniq = self.GetUniqueName()
        output_fname = tools.get_output_filename('csf.%s' % uniq)
        input_fname = tools.get_output_filename('input.%s' % uniq)
        tools.write_file(input_fname, input_data)
        stdout = self.csf.sign_firmware(
            outfile=output_fname,
            firmware=input_fname)
        if stdout is not None:
            data = tools.read_file(output_fname)
        else:
            # Bintool is missing; just use 4KB of zero data
            self.record_missing_bintool(self.csf)
            data = tools.get_bytes(0, 4096)
        return data

    def ObtainContents(self):
        data = self.GetCsf(False)
        if data is None:
            return False
        self.SetContents(data)
        return True

    def ProcessContents(self):
        # The blob may have changed due to WriteSymbols()
        data = self.GetCsf(True)
        return self.ProcessContentsUpdate(data)

    def AddBintools(self, btools):
        self.csf = self.AddBintool(btools, 'csf')
