# SPDX-License-Identifier: GPL-2.0+
#
# Copyright 2021 Google LLC
# Written by Simon Glass <sjg@chromium.org>

obj-$(CONFIG_$(SPL_TPL_)USB_GADGET) += cdns3/
obj-$(CONFIG_$(SPL_TPL_)USB_GADGET) += dwc3/
obj-$(CONFIG_$(SPL_TPL_)USB_HOST) += dwc3/
obj-$(CONFIG_$(SPL_TPL_)USB_GADGET) += common/
obj-$(CONFIG_$(SPL_TPL_)USB_HOST) += common/
obj-$(CONFIG_$(SPL_TPL_)USB_EMUL) += emul/
obj-$(CONFIG_$(SPL_TPL_)USB_HOST_ETHER) += eth/
obj-$(CONFIG_USB_DEVICE) += gadget/
obj-$(CONFIG_$(SPL_TPL_)USB_GADGET) += gadget/
obj-$(CONFIG_$(SPL_TPL_)USB_GADGET) += gadget/udc/
obj-$(CONFIG_$(SPL_TPL_)USB_HOST) += host/
obj-$(CONFIG_$(SPL_TPL_)USB_MTU3) += mtu3/
obj-y += musb/
obj-$(CONFIG_$(SPL_TPL_)MUSB_NEW) += musb-new/
obj-y += phy/
obj-y += ulpi/
