#
# Copyright (c) 2014 Google, Inc
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += cpu.o
obj-y += car.o
obj-y += early_init.o
obj-y += early_me.o
obj-y += me_status.o
obj-y += microcode_intel.o
obj-y += mrccache.o
obj-y += report_platform.o
obj-y += sdram.o
