#
# Copyright (c) 2017 Google, Inc
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_CHROMEOS) += cmd/
obj-$(CONFIG_CHROMEOS) += crypto/
obj-$(CONFIG_CROS_FLAG) += flag/
obj-$(CONFIG_CHROMEOS) += fwstore/
obj-$(CONFIG_CHROMEOS) += lib/
obj-$(CONFIG_CHROMEOS) += nvdata/
obj-$(CONFIG_CHROMEOS) += resource/
obj-$(CONFIG_CHROMEOS) += stage/
obj-$(CONFIG_CHROMEOS) += vboot/
# obj-y += $(CONFIG_SYS_SOC)/
obj-$(CONFIG_SANDBOX) += soc/sandbox/
obj-$(CONFIG_X86) += soc/x86/
