# SPDX-License-Identifier: GPL-2.0
# Copyright 2021 Google LLC
# Written by Simon Glass <sjg@chromium.org>

import os
import pytest
import u_boot_utils

def mkdir_cond(dirname):
    """Create a directory if it doesn't already exist

    Args:
        dirname: Name of directory to create
    """
    if not os.path.exists(dirname):
        os.mkdir(dirname)


def bootflow_image(u_boot_console):
    """Create a 20MB disk image with a single FAT partition"""
    cons = u_boot_console
    fname = os.path.join(cons.config.build_dir, 'mmc.img')
    mnt = os.path.join(cons.config.persistent_data_dir, 'mnt')
    mkdir_cond(mnt)

    u_boot_utils.run_and_log(cons, 'qemu-img create %s 20M' % fname)
    u_boot_utils.run_and_log(cons, 'sudo sfdisk %s' % fname,
                             stdin=b'type=c')

    loop = None
    mounted = False
    try:
        out = u_boot_utils.run_and_log(cons,
                                       'sudo losetup --show -f -P %s' % fname)
        loop = out.strip()
        fatpart = '%sp1' % loop
        u_boot_utils.run_and_log(cons, 'sudo mkfs.vfat %s' % fatpart)
        u_boot_utils.run_and_log(
            cons, 'sudo mount -o loop %s %s -o uid=%d,gid=%d' %
            (fatpart, mnt, os.getuid(), os.getgid()))
        mounted = True
    except:
        if mounted:
            u_boot_utils.run_and_log(cons, 'sudo umount %s' % mnt)
        if loop:
            u_boot_utils.run_and_log(cons, 'sudo losetup -d %s' % loop)
        raise
    yield mnt

    script = '''
# extlinux.conf generated by appliance-creator
ui menu.c32
menu autoboot Welcome to Fedora-Workstation-armhfp-31-1.9. Automatic boot in # second{,s}. Press a key for options.
menu title Fedora-Workstation-armhfp-31-1.9 Boot Options.
menu hidden
timeout 20
totaltimeout 600

label Fedora-Workstation-armhfp-31-1.9 (5.3.7-301.fc31.armv7hl)
	kernel /$vmlinux
	append ro root=UUID=9732b35b-4cd5-458b-9b91-80f7047e0b8a rhgb quiet LANG=en_US.UTF-8 cma=192MB cma=256MB
	fdtdir /dtb-5.3.7-301.fc31.armv7hl/
	initrd /$initrd
'''
    ext = os.path.join(mnt, 'extlinux')
    mkdir_cond(ext)

    with open(os.path.join(ext, 'extlinux.conf'), 'w') as fd:
        print(script, file=fd)

    u_boot_utils.run_and_log(cons, 'sudo umount %s' % mnt)
    u_boot_utils.run_and_log(cons, 'sudo losetup -d %s' % loop)


def xtest_bootflow(bootflow_image, u_boot_console):
    """Test that the "help" command can be executed."""
    cons = u_boot_console
    cons.run_command('ut bootdevice')
