# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2015 Mateusz Kulikowski <mateusz.kulikowski@gmail.com>

obj-$(CONFIG_SOC_APQ8096) += clock-apq8096.o
obj-$(CONFIG_SOC_APQ8096) += sysmap-apq8096.o
obj-$(CONFIG_SOC_APQ8016) += clock-apq8016.o
obj-$(CONFIG_SOC_APQ8016) += sysmap-apq8016.o
obj-$(CONFIG_SOC_APQ8016) += pinctrl-apq8016.o
obj-$(CONFIG_SOC_APQ8016) += pinctrl-snapdragon.o
obj-$(CONFIG_SOC_APQ) += misc.o
obj-$(CONFIG_SOC_APQ) += clock-snapdragon.o
obj-$(CONFIG_SOC_APQ) += dram.o

obj-$(CONFIG_SOC_SDA845) += sysmap-sda845.o
