/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "cmdsock.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(StartReq, StartReq, AUTO)


PB_BIND(StartResp, StartResp, AUTO)


PB_BIND(Puts, Puts, 2)


PB_BIND(RunCmdReq, RunCmdReq, 2)


PB_BIND(RunCmdResp, RunCmdResp, AUTO)


PB_BIND(Message, Message, 2)



