# SPDX-License-Identifier: GPL-2.0+
#
# Copyright 2021 Google, Inc
#
# SPDX-License-Identifier:	GPL-2.0+
#
# Awk script to parse a text file containing an environment and convert it
# to a C string which can be compiled into U-Boot.

# We output a double quote before starting, and again when we finish so that
# all output is quoted.
BEGIN {
	# env holds the env variable we are currently processing
	env = "";
	ORS = ""
	print "\""
}

# Skip empty lines, as these are generated by the clang preprocessor
NF {
	# Quote quotes
	gsub("\"", "\\\"")

	# Is this the start of a new environment variable?
	if (match($0, "^([^ =][^ =]*)=(.*)", arr)) {
		if (length(env) != 0) {
			# Record the value of the variable now completed
			vars[var] = env
		}
		var = arr[1]
		env = arr[2]

		# Deal with +=
		if (match(var, "(.*)[+]$", var_arr)) {
			var = var_arr[1]
			env = vars[var] env
		}
	} else {
		# Change newline to \n
		env = env "\\n" $0;
	}
}

END {
	# Record the value of the variable now completed. If the variable is
	# empty it is not set.
	if (length(env) != 0) {
		vars[var] = env
	}

	# Print out all the variables
	for (var in vars) {
		print var "=" vars[var] "\\0";
	}
	print "\"\n"
}
