# SPDX-License-Identifier: GPL-2.0+
#
# Copyright 2025 Canonical Ltd
# Written by Simon Glass <simon.glass@canonical.com>

obj-y += bootctl-uclass.o
obj-y += bootctl.o
obj-y += efi_os.o
obj-y += extlinux.o
obj-y += logic.o
obj-y += simple_meas.o
obj-y += simple_state.o
obj-y += simple_ui.o
obj-y += util.o
