# SPDX-License-Identifier: GPL-2.0+
# Copyright 2020 Google LLC

import console

class Dut:
    """Individual board in the lab, upon which we want to run tests.

    DUT stands for device-under-test. It means the device that is being tested.

    If a board can be used for different builds, it should still only appear
    once in the lab.

    DUTs have a particular hardware configuration (e.g processor, memory) and
    have connections with in the lab (e.g. for serial UART).

    Properties:
        _parent: Parent object (e.g. a Lab)
        _name: Name of the DUT (e.g. 'rpi_3')
        _desc: Description of the DUT (e.g. 'Raspberry Pi 3b')
        _cons: Console to talk to the DUT
    """
    def __init__(self, parent, name):
        self._parent = parent
        self._name = name
        self._desc = None
        self._cons = None

    def load(self, yam):
        self._desc = yam.get('desc')
        cons_yam = yam.get('console')
        if cons_yam:
            self._cons = console.Console(self)
            self._cons.load(cons_yam)

    def __str__(self):
        return 'dut %s' % self._name

    def Raise(self, msg):
        self._parent.Raise('%s: %s' % (str(self), msg))

    def show(self):
        print('%15s  %s' % (self._name, self._desc))

    def emit_tbot(self):
        vals = {
            'dut_name': str(self),
            'uart': self._cons.get_uart()
            }
        out = '''# Generated by labman from {dut_name}
import time

import tbot
from tbot.machine import board, channel, connector, linux
from tbot.tc import git, shell, uboot
from ykush import Ykush
from sdwire import Sdwire

class Rpi3UBootBuilder(uboot.UBootBuilder):
    name = "rpi_3"
    defconfig = "rpi_3_32b_defconfig"
    toolchain = "armv7-a"


class Rpi3(
    connector.ConsoleConnector,
    board.PowerControl,
    board.Board,
    Ykush,
    Sdwire,
):
    name = "Raspberry Pi 3b"
    ykush_serial = "YK17698"
    ykush_port = "1"

    sdwire_serial = "sdwire-18"

    ether_mac = "b8:27:eb:b4:f9:f2"

    mount_uuid = "B529-9710"
    mount_point = "rpi3_b_boot"

    def poweron(self) -> None:
        """Procedure to turn power on."""
        self.sdwire_dut()
        self.ykush_reset()

    def poweroff(self) -> None:
        """Procedure to turn power off."""
        self.ykush_off()
        self.sdwire_ts()

    def connect(self, mach) -> channel.Channel:
        """Connect to the board\'s serial interface."""
        return mach.open_channel("picocom", "-b", "115200", "{uart}")

    def flash(self, repo: git.GitRepository) -> None:
        board = self
        host = self.host
        board.poweroff()
        out = host.exec0("whoami")
        done = False
        for i in range(5):
            out = ""
            try:
                retcode, out = host.exec("mount", "UUID=%s" % self.mount_uuid)
                done = retcode == 0
                if done:
                    break
            except Exception as e:
                pass
            if "already mounted" in out:
                # If it is already mounted, try to unmount it first. It may have
                # been mounted by another user so we won't have the access we
                # need. If this gives an error then it might be transient, e.g.
                # "Operation not permitted" is sometimes returned when there are
                # I/O errors on the device.
                host.exec("umount", "UUID=%s" % self.mount_uuid)
            time.sleep(1)
        if not done:
            raise ValueError("Cannot access mount '%s'" % board.mount_uuid)

        # Enable the UART and fix the GPU frequency so it works correctly
        config = "/media/%s/config.txt" % self.mount_point
        host.exec0("sed", "-i", "/enable_uart/c\enable_uart = 1", config)
        retcode, _ = host.exec("grep", "-q", "^gpu_freq=250", config)
        if retcode:
            host.exec0("bash", "-c", "echo gpu_freq=250 >>%s" % config)

        # Copy U-Boot over from the build directory
        shell.copy(repo / "u-boot.bin",
                   host.fsroot / ("/media/%s/rpi3-u-boot.bin" %
                                  self.mount_point))

        host.exec0("umount", "UUID=%s" % self.mount_uuid)

        board.sdwire_dut()


class Rpi3UBoot(
    board.Connector,
    board.UBootAutobootIntercept,
    board.UBootShell,
):
    prompt = "=> "
    build = Rpi3UBootBuilder()


class Rpi3Linux(
    board.Connector,
    board.LinuxBootLogin,
    linux.Bash,
):
    username = "pi"
    password = "raspberry"


BOARD = Rpi3
UBOOT = Rpi3UBoot
LINUX = Rpi3Linux
'''.format(**vals)

        print(out, end='')
