# SPDX-License-Identifier: GPL-2.0+
#
# Copyright 2025 Simon Glass <sjg@chromium.org>

# We don't need anything here as the files in this directory are directly built
# by the main Makefile
#
# We cannot use 'obj-y += ulib/' in test/Makefile since we won't want these
# files included in the main build.

